# Generated by Django 4.2.7 on 2024-01-20 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=1)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
