# Generated by Django 4.2.7 on 2024-01-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprintapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='state',
            new_name='completed',
        ),
    ]
