# Generated by Django 4.2.7 on 2024-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintapp', '0002_rename_state_userstory_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
